-- =============================================================================
-- MIGRACIÓN DE ARQUITECTURA DEFINITIVA DE VENTAS E IDEMPOTENCIA
-- Fecha: 18/09/2026
-- Proyecto: StockApp Electron / Supabase PostgreSQL
-- Archivo: database/20260918_fix_sale_ids_and_idempotency.sql
-- 
-- IMPORTANTE: NO EJECUTAR AUTOMÁTICAMENTE EN PRODUCCIÓN.
-- ESTE SCRIPT DEBE REVISARSE Y EJECUTARSE MANUALMENTE EN EL SQL EDITOR DE SUPABASE.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PASO 1: AGREGAR COLUMNAS DE IDEMPOTENCIA (UUID GLOBAL DE OPERACIÓN)
-- -----------------------------------------------------------------------------
ALTER TABLE public.tickets 
ADD COLUMN IF NOT EXISTS client_transaction_id UUID;

ALTER TABLE public.ventas 
ADD COLUMN IF NOT EXISTS client_transaction_id UUID;

-- Crear restricción UNIQUE parcial en tickets para garantizar idempotencia atómica
CREATE UNIQUE INDEX IF NOT EXISTS idx_tickets_client_transaction_id 
ON public.tickets (client_transaction_id) 
WHERE client_transaction_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- PASO 2: SINCRONIZACIÓN INICIAL ÚNICA DE SECUENCIAS (POSTGRESQL REPAIR)
-- Sincroniza las secuencias 'tickets_id_seq' y 'ventas_id_seq' al valor máximo actual (96 y 66).
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_tickets_max bigint;
    v_ventas_max bigint;
    v_seq_tickets text;
    v_seq_ventas text;
BEGIN
    SELECT COALESCE(MAX(id), 0) INTO v_tickets_max FROM public.tickets;
    SELECT COALESCE(MAX(id), 0) INTO v_ventas_max FROM public.ventas;

    v_seq_tickets := pg_get_serial_sequence('public.tickets', 'id');
    IF v_seq_tickets IS NOT NULL THEN
        PERFORM setval(v_seq_tickets, GREATEST(v_tickets_max, 1), true);
    ELSE
        BEGIN
            PERFORM setval('public.tickets_id_seq', GREATEST(v_tickets_max, 1), true);
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END IF;

    v_seq_ventas := pg_get_serial_sequence('public.ventas', 'id');
    IF v_seq_ventas IS NOT NULL THEN
        PERFORM setval(v_seq_ventas, GREATEST(v_ventas_max, 1), true);
    ELSE
        BEGIN
            PERFORM setval('public.ventas_id_seq', GREATEST(v_ventas_max, 1), true);
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END IF;
END $$;

-- Asegurar modo GENERATED BY DEFAULT para mantener compatibilidad histórica
DO $$
BEGIN
    BEGIN
        ALTER TABLE public.tickets ALTER COLUMN id SET GENERATED BY DEFAULT;
    EXCEPTION WHEN OTHERS THEN NULL; END;

    BEGIN
        ALTER TABLE public.ventas ALTER COLUMN id SET GENERATED BY DEFAULT;
    EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;

-- -----------------------------------------------------------------------------
-- PASO 3: NUEVA VERSIÓN IDEMPOTENTE DE 'procesar_venta_multiproducto'
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.procesar_venta_multiproducto(
    p_items jsonb,
    p_metodo_pago text DEFAULT 'Efectivo',
    p_cliente text DEFAULT 'Consumidor Final',
    p_client_transaction_id uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_item jsonb;
    v_producto_id bigint;
    v_cantidad numeric;
    v_total_item numeric;
    v_stock_actual numeric;
    v_nombre_prod text;
    v_subtotal numeric := 0;
    v_ticket_id bigint;
BEGIN
    -- 1. Validar payload de ítems
    IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'El carrito de productos está vacío.');
    END IF;

    -- 2. VERIFICACIÓN DE IDEMPOTENCIA ATÓMICA
    -- Si se proporciona un client_transaction_id y la venta ya fue procesada anteriormente,
    -- NO se vuelve a descontar stock ni a crear registros. Se retorna la respuesta original.
    IF p_client_transaction_id IS NOT NULL THEN
        SELECT id INTO v_ticket_id
        FROM public.tickets
        WHERE client_transaction_id = p_client_transaction_id;

        IF FOUND THEN
            SELECT total INTO v_subtotal FROM public.tickets WHERE id = v_ticket_id;
            RETURN jsonb_build_object(
                'success', true,
                'ticket_id', v_ticket_id,
                'total', v_subtotal,
                'idempotent_replay', true
            );
        END IF;
    END IF;

    -- 3. VALIDACIÓN DE STOCK Y BLOQUEO DE FILAS (FOR UPDATE en orden ascendente para evitar deadlocks)
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) ORDER BY (value->>'producto_id')::bigint ASC LOOP
        v_producto_id := (v_item->>'producto_id')::bigint;
        v_cantidad := (v_item->>'cantidad')::numeric;
        v_total_item := (v_item->>'total')::numeric;

        SELECT stock, nombre INTO v_stock_actual, v_nombre_prod
        FROM public.productos
        WHERE id = v_producto_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RETURN jsonb_build_object('success', false, 'error', 'Producto ID ' || v_producto_id || ' no existe.');
        END IF;

        IF v_stock_actual < v_cantidad THEN
            RETURN jsonb_build_object(
                'success', false, 
                'error', 'STOCK_INSUFICIENTE: Producto "' || v_nombre_prod || '" (ID ' || v_producto_id || ') tiene stock ' || v_stock_actual || ', pero se solicitaron ' || v_cantidad
            );
        END IF;

        v_subtotal := v_subtotal + v_total_item;
    END LOOP;

    -- 4. INSERT EN TABLA TICKETS (CON client_transaction_id)
    INSERT INTO public.tickets (fecha, metodo_pago, total, productos, tipo, subtotal, cliente, client_transaction_id)
    VALUES (NOW(), p_metodo_pago, v_subtotal, p_items, 'Venta', v_subtotal, p_cliente, p_client_transaction_id)
    RETURNING id INTO v_ticket_id;

    -- 5. DESCUENTO DE STOCK E INSERT EN TABLA VENTAS
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
        v_producto_id := (v_item->>'producto_id')::bigint;
        v_cantidad := (v_item->>'cantidad')::numeric;
        v_total_item := (v_item->>'total')::numeric;

        UPDATE public.productos
        SET stock = stock - v_cantidad
        WHERE id = v_producto_id;

        INSERT INTO public.ventas (producto_id, cantidad, total, metodo_pago, cliente, fecha, client_transaction_id)
        VALUES (v_producto_id, v_cantidad, v_total_item, p_metodo_pago, p_cliente, NOW(), p_client_transaction_id);
    END LOOP;

    RETURN jsonb_build_object(
        'success', true,
        'ticket_id', v_ticket_id,
        'total', v_subtotal,
        'idempotent_replay', false
    );
EXCEPTION 
    WHEN unique_violation THEN
        -- Protección adicional contra carreras concurrentes exactas en el índice de idempotencia
        IF p_client_transaction_id IS NOT NULL THEN
            SELECT id INTO v_ticket_id FROM public.tickets WHERE client_transaction_id = p_client_transaction_id;
            IF FOUND THEN
                SELECT total INTO v_subtotal FROM public.tickets WHERE id = v_ticket_id;
                RETURN jsonb_build_object(
                    'success', true,
                    'ticket_id', v_ticket_id,
                    'total', v_subtotal,
                    'idempotent_replay', true
                );
            END IF;
        END IF;
        RETURN jsonb_build_object('success', false, 'error', SQLERRM);
    WHEN OTHERS THEN
        RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;
