-- =============================================================================
-- PARCHE DE CORRECCIÓN CONTROLADA - PROBLEMA 1 (VENTAS) Y PROBLEMA 2 (CATEGORIAS)
-- Fecha: 14/08/2026
-- =============================================================================

-- 1. CORRECCIÓN PROBLEMA 1 (VENTAS - IDENTITY MODE)
-- Permite que Supabase acepte los IDs explícitos sincronizados desde SQLite/offlineQueue
ALTER TABLE public.ventas ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. CORRECCIÓN PROBLEMA 2 (CATEGORIAS - PERMISOS WEB NEXT.JS)
-- Otorga permiso SELECT al rol anon/authenticated para resolver "permission denied for table categorias"
GRANT SELECT ON TABLE public.categorias TO anon, authenticated;

-- Garantiza que RLS permita lectura pública sobre la tabla categorias
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir lectura publica a anon" ON public.categorias;
CREATE POLICY "Permitir lectura publica a anon" 
ON public.categorias 
FOR SELECT 
TO anon, authenticated 
USING (true);
